// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as library$0 from "../../../../Ricori/finoka/desktop/internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as plugins$0 from "../../../../Ricori/finoka/desktop/internal/plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as selfupdate$0 from "../../../../Ricori/finoka/desktop/internal/selfupdate/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "editor:request-close": string;
            "files:dropped": string[] | null;
            "home:refresh": boolean;
            "library:changed": library$0.Entry[] | null;
            "plugins:changed": plugins$0.Change;
            "plugins:download-log": plugins$0.DownloadLog;
            "update:ready": { [_ in string]?: string } | null;
            "update:status": selfupdate$0.Status;
        }
    }
}
