// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AdminKeys(): $CancellablePromise<$models.AdminKey[] | null> {
    return $Call.ByID(3379938318);
}

/**
 * AdoptCloudEntry makes a finished cloud entry editable on a machine that does
 * not have the video at all. The subtitles are the deliverable; the media is
 * only needed to play them back, so the library records a placeholder for the
 * fingerprint and the document hangs on that. Associating a video later fills
 * the same entry in while retaining the subtitle record's identity. Returns the
 * local media id to open.
 */
export function AdoptCloudEntry(videoID: string): $CancellablePromise<string> {
    return $Call.ByID(3065162032, videoID);
}

/**
 * AdoptLibraryEntry projects a finished cloud entry onto local media that this
 * installation never ran the task for -- the subtitles were produced on another
 * machine, or before a reinstall, and the video has only just been imported or
 * relinked here. Without it the card correctly reports the cloud copy while
 * still offering to transcribe the media all over again.
 */
export function AdoptLibraryEntry(videoID: string, localID: string): $CancellablePromise<void> {
    return $Call.ByID(4232335274, videoID, localID);
}

export function CancelTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(996890780, taskID);
}

export function Capabilities(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2972300145);
}

export function CreateAdminKey(name: string, key: string, remaining: number): $CancellablePromise<$models.IssuedAdminKey> {
    return $Call.ByID(3753253657, name, key, remaining);
}

export function DeleteAdminKey(identifier: string): $CancellablePromise<void> {
    return $Call.ByID(2519480654, identifier);
}

export function DeleteLibraryEntry(identifier: string): $CancellablePromise<void> {
    return $Call.ByID(1068790133, identifier);
}

export function Library(): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(2510052966);
}

export function ListTasks(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4110537819);
}

export function Login(backend: string, key: string): $CancellablePromise<$models.Session> {
    return $Call.ByID(576687776, backend, key);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3482298597);
}

export function RefreshSession(): $CancellablePromise<$models.Session> {
    return $Call.ByID(383730666);
}

export function ResumeTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4043928877, taskID);
}

export function RetryTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(394722618, taskID);
}

export function Session(): $CancellablePromise<$models.Session> {
    return $Call.ByID(509849469);
}

export function StartTask(localID: string, options: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1031828528, localID, options);
}

/**
 * SyncLocalTask reads only artifacts reported by the Local Provider and only
 * when their resolved paths remain under Finoka's task root.
 */
export function SyncLocalTask(taskID: string, localID: string, fingerprint: string, title: string, duration: number): $CancellablePromise<$models.Entry> {
    return $Call.ByID(4271541350, taskID, localID, fingerprint, title, duration);
}

export function TaskArtifacts(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2748179937, taskID);
}

export function TaskEvents(taskID: string, afterCursor: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1856655079, taskID, afterCursor);
}

export function TaskStatus(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3360738780, taskID);
}

/**
 * ThumbnailDataURL returns the cover of a cloud library entry, mirroring the
 * local library accessor of the same name so the renderer treats both alike.
 * The bytes are cached on disk: a cover never changes for a given upload, and
 * the cloud library is re-read on every refresh.
 */
export function ThumbnailDataURL(videoID: string): $CancellablePromise<string> {
    return $Call.ByID(2358810250, videoID);
}

export function UpdateAdminKey(identifier: string, name: string, remaining: number): $CancellablePromise<$models.AdminKey> {
    return $Call.ByID(207994712, identifier, name, remaining);
}
