// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDownload interrupts the running download. Killing the process is what
 * actually stops it: yt-dlp has no gentler protocol, and the context it runs
 * under is already the timeout's, so cancelling that covers both paths.
 */
export function CancelDownload(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(1179173450, pluginID);
}

export function ClearCookies(pluginID: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(2834511644, pluginID);
}

/**
 * ClearDownloadLog empties the retained log. It clears the host's buffer, not
 * just the page's view: the page re-fetches on every mount, so wiping only the
 * DOM would bring the whole log back the next time the user navigated away and
 * returned.
 */
export function ClearDownloadLog(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(3187234109, pluginID);
}

/**
 * Document returns the stored EditDocument for a media entry. The plugin names
 * the media by the id media.list handed it, never by path.
 */
export function Document(pluginID: string, mediaID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2177955241, pluginID, mediaID);
}

/**
 * DownloadLogLines returns the running -- or most recently finished -- run's
 * output, so a page can render the history it missed. It survives past the end
 * of a run deliberately: coming back after a download finished should still show
 * what happened, and the buffer is cleared when the next one starts.
 */
export function DownloadLogLines(pluginID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3038065417, pluginID);
}

/**
 * ExportAudio is a structured FFmpeg capability. Plugins select a Finoka media
 * ID and an output format; the host owns input resolution, arguments, the save
 * dialog, temporary files, and final publication.
 */
export function ExportAudio(pluginID: string, mediaID: string, format: string): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(2716183520, pluginID, mediaID, format);
}

/**
 * ExportVideo burns plugin-supplied ASS into a library video. The plugin owns
 * the subtitle text and the range; the host owns FFmpeg, the encoding
 * settings, the save dialog and atomic publication, exactly as the editor's
 * own export does.
 */
export function ExportVideo(pluginID: string, mediaID: string, fileName: string, ass: string, t0: number, t1: number, scaleHeight: number): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(3299501749, pluginID, mediaID, fileName, ass, t0, t1, scaleHeight);
}

/**
 * Install accepts a .finoka-plugin ZIP or an unpacked plugin directory. The
 * directory form is intended for developer workflows and automated tests.
 */
export function Install(path: string): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(4213420995, path);
}

export function List(): $CancellablePromise<$models.InstalledPlugin[] | null> {
    return $Call.ByID(100861768);
}

/**
 * LoadDownloaderSettings reports what the downloader is configured with. The
 * cookie jar is summarised, never returned.
 */
export function LoadDownloaderSettings(pluginID: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(1574118078, pluginID);
}

export function MediaList(pluginID: string): $CancellablePromise<$models.MediaSummary[] | null> {
    return $Call.ByID(3561990828, pluginID);
}

export function PageHTML(pluginID: string, toolID: string): $CancellablePromise<string> {
    return $Call.ByID(1769821126, pluginID, toolID);
}

export function PickAndInstall(): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(787520081);
}

/**
 * RunYTDLP executes plugin-supplied yt-dlp arguments from a closed safe set for
 * public YouTube and Twitch URLs. The host still owns tool resolution, the
 * output path, FFmpeg wiring and the final media-library import.
 */
export function RunYTDLP(pluginID: string, rawURL: string, pluginArgs: string[] | null): $CancellablePromise<$models.DownloadedMedia> {
    return $Call.ByID(2793227616, pluginID, rawURL, pluginArgs);
}

export function SaveCookies(pluginID: string, content: string): $CancellablePromise<$models.DownloaderSettings> {
    return $Call.ByID(1413208172, pluginID, content);
}

/**
 * SaveDocument writes the editable part of a document back. The payload is
 * rebuilt from the fields the sidecar accepts, so a plugin can neither invent
 * document fields nor drop the revision that guards a concurrent editor save.
 */
export function SaveDocument(pluginID: string, mediaID: string, document: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(395591932, pluginID, mediaID, document);
}

/**
 * SaveSubtitleFile publishes plugin-built subtitle text through the host save
 * dialog. The plugin picks the content and a suggested name; the user picks
 * where it lands, and the host owns the extension.
 */
export function SaveSubtitleFile(pluginID: string, fileName: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(1114008791, pluginID, fileName, content);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(779905873, id, enabled);
}

export function Uninstall(id: string, removeData: boolean): $CancellablePromise<void> {
    return $Call.ByID(2590740258, id, removeData);
}
