// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Get returns the stored sheet, or "" when nothing has been saved yet. The
 * empty case is deliberately not filled in here: the built-in styles live in
 * the frontend, and duplicating them in Go would give them two sources of truth.
 */
export function Get(): $CancellablePromise<string> {
    return $Call.ByID(1032862263);
}

export function Save(text: string): $CancellablePromise<string> {
    return $Call.ByID(2267027880, text);
}
