// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface State {
    "schema": number;
    "homeTheme": string;
    "editorTheme": string;
    "sidebarCollapsed": boolean;
    "libraryView": string;
    "bounds": { [_ in string]?: WindowBounds } | null;
}

export interface WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
    "fullScreen": boolean;
}
