// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Get(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(4031626703);
}

/**
 * Save replaces the whole history. The renderer owns ordering and dedup, so a
 * partial merge here would only fight it.
 */
export function Save(entries: any[] | null): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1064688944, entries);
}
